[package]
name = "zram-generator"
version = "0.3.0"
authors = ["Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>",
           "Igor Raits <i.gnatenko.brain@gmail.com>",
           "наб <nabijaczleweli@gmail.com>"]
license = "MIT"
description = "Systemd unit generator for zram swap devices."
homepage = "https://github.com/systemd/zram-generator"
edition = "2018"

[dependencies]
anyhow = ">=1.0.12, <1.0.39"
clap = { version = "2.33", default-features = false }
liboverdrop = "0.0.2"
rust-ini = ">=0.13, <0.17"
log = { version = "0.4", features = ["std"] }
eval = "0.4"

[dev-dependencies]
tempfile = "3"
fs_extra = ">=1.1, <1.3"

[profile.release]
lto = true
